# Clinical summarization configuration
# Usage: python -m locallighteval.main --config-name=clinical_summarization

defaults:
  - config  # Inherit from base config.yaml
  - _self_

# Override base settings for clinical summarization
experiment_name: "clinical_summarization"
mode: summarization

# Data settings - update the path as needed
data:
  input_path: "/ssd-shared/report-distillation.json"
  max_samples: 100  # Limit for testing

# Model optimized for summarization (base model for now - LoRA merging needed for fine-tuned version)
model:
  name: "/ssd-shared/qwen/qwen3-4b-clinical-RL-tuned"  # Base model that the LoRA was trained on
  gpu_memory_utilization: 0.95
  visible_devices: "7"
  max_model_len: 2048


# Summarization-specific settings
summarization:
  output_suffix: "_clinical_summaries"
  save_original_text: true