# Clinical summarization configuration
# Usage: python -m locallighteval.main --config-name=clinical_summarization

defaults:
  - config  # Inherit from base config.yaml
  - _self_

# Override base settings for clinical summarization
experiment_name: "clinical_summarization"
mode: summarization

# Data settings - update the path as needed
data:
  input_path: "/ssd-shared/report-distillation.json"
  max_samples: 100  # Limit for testing

# Model optimized for summarization (base model for now - LoRA merging needed for fine-tuned version)
model:
  name: "Qwen/Qwen3-4B-Instruct-2507"  # Base model that the LoRA was trained on
  gpu_memory_utilization: 0.95
  visible_devices: "7"
  # TODO: Merge LoRA adapter from /ssd-shared/ryans_output/random_text_no_lower_limit/checkpoint-1600


# Summarization-specific settings
summarization:
  output_suffix: "_clinical_summaries"
  save_original_text: true