# @package inference
max_tokens: 10
temperature: 0.0
top_p: 1.0
top_k: -1
batch_size: 16
instruction: "Classify the following text as positive (1) or negative (0). Here are some examples:\n\nText: This is great!\nLabel: 1\n\nText: This is terrible.\nLabel: 0\n\nNow classify this text. Respond with only the number."